default: &default
  adapter: postgresql
  encoding: unicode
  database: adamzucker
  pool: 5
  username: adamzucker
  password: staybreezy

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
