test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

# Use rails credentials:edit to set the AWS secrets (as aws:access_key_id|secret_access_key)
# amazon:
#   service: S3
#   access_key_id: <%= Rails.application.credentials.dig(:aws, :access_key_id) %>
#   secret_access_key: <%= Rails.application.credentials.dig(:aws, :secret_access_key) %>
#   region: us-east-1
#   bucket: your_own_bucket

google:
  service: GCS
  project: work-thangs
  credentials: <%= ENV['GOOGLE_APPLICATION_CREDENTIALS'].as_json %>
  bucket: adamzucker-io
google_dev:
  service: GCS
  project: work-thangs
  credentials: <%= Rails.root.join("config/secrets/adamzucker-io.json") %>
  bucket: adamzucker-io